apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  oidc.config: |
    name: Cognito
    issuer: COGNITO_IDP_ISSUER_URL
    clientID: CLIENT_ID_FROM_COGNITO # ArgoCD app client ID
    clientSecret: CLIENT_SECRET_FROM_COGNITO
    requestedScopes: ["openid", "profile", "email"]
    customGroupClaimName: "cognito:groups"
  url: argoCD_domain_name
